GET http://localhost:3000/users

###
GET http://localhost:3000/users/

###

POST http://localhost:3000/users/new
Content-Type: application/json

{
    "username": "Marko123",
    "password": "test123",
    "prenom": "Marko",
    "nom": "Perotic",
    "phone": "514 123 4567",
    "email": "test@test.com"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "FabbyStabby",
    "password": "123"
}

###
 
GET http://localhost:3000/rendezVousDispo?date=12/12/2022


###

POST http://localhost:3000/rendezVousDispo/new
Content-Type: application/json

{
    "date": "12/12/2022",
    "time": "13:30",
    "available": true
}

###

POST http://localhost:3000/rendezVous/new
Content-Type: application/json

{
    "date": "12/12/2022",
    "time": "13:30",
    "username": "FabbyStabby"
}

###

PUT http://localhost:3000/rendezVousDispo/updateAvailable
Content-Type: application/json

{
    "date": "12/12/2022",
    "time": "13:30",
    "available": true
}

###

PUT http://localhost:3000/rendezVousDispo/updateAvailable
Content-Type: application/json

{
    "date": "12/12/2022",
    "time": "14:30",
    "available": false
}

###

DELETE http://localhost:3000/rendezVous/delete?username=FabbyStabby

###

GET http://localhost:3000/rendezVous?username=FabbyStabby